from __future__ import annotations

import io
import logging
import re
import zipfile
from datetime import date, datetime
from typing import Dict, Iterable, List, Optional

from openpyxl import load_workbook

logger = logging.getLogger(__name__)


CR_ID_RE = re.compile(r"[RSC][1-9][-sw]\d{6,7}(?:r\d{1})?", re.IGNORECASE)

# Mirrors CR_ID_RE but exposes the year as a capture group; keep in sync.
# 7-digit ids (RAN4) drop the third sequence digit so the year still
# sits at offset 3-4.
_TDOC_YEAR_GROUP_RE = re.compile(r"[RSC][1-9][-sw](\d{2})\d{4,5}(?:r\d{1})?$", re.IGNORECASE)


def tdoc_id_year(tdoc_id: str) -> int | None:
    """Return the 2-digit year embedded in ``tdoc_id``, or ``None``.

    Centralises the structural assumption that the year sits at offset 3-4
    inside the canonical CR_ID_RE shape, so SQL filters don't have to hard-code
    a ``substr`` offset that would silently desync if the convention changes.
    """
    match = _TDOC_YEAR_GROUP_RE.fullmatch(tdoc_id)
    if not match:
        return None
    return int(match.group(1))

# Substrings that disambiguate the real header row from a title row that
# happens to mention "tdoc" (e.g. "TDoc List — RAN5#111").
_HEADER_ROW_MARKERS = frozenset(
    {"title", "source", "type", "status", "spec", "version", "release"}
)


def _is_header_row(potential: Dict[str, int]) -> bool:
    has_tdoc = any("tdoc" in key for key in potential)
    if not has_tdoc:
        return False
    return any(marker in key for key in potential for marker in _HEADER_ROW_MARKERS)


def normalize_header(value: object) -> str:
    """Normalize a cell header value to lowercase whitespace-normalized text."""
    if value is None:
        return ""
    text = str(value).strip().lower()
    return re.sub(r"\s+", " ", text)


def to_text(value: object) -> Optional[str]:
    """Convert a cell value to trimmed text, returning ``None`` for empty/missing.

    Distinguishes "missing" (cell was ``None``) from "empty" (cell was ``""``
    or whitespace) — both surface as ``None`` here so callers don't have to
    repeat the falsy check and ORM nullable columns stay correctly typed.
    """
    if value is None:
        return None
    text = str(value).strip()
    return text if text else None


def _parse_date_cell(value: object) -> date | None:
    """Parse an XLSX cell value as a ``date``.

    Handles ``datetime``/``date`` instances directly and the string formats
    observed in upstream 3GPP TDoc list XLSX files:

      * ``YYYY-MM-DD`` (ISO date)
      * ``YYYY/MM/DD`` (ISO with slashes)
      * ``DD/MM/YYYY HH:MM:SS`` (European datetime, e.g. ``02/04/2026 15:24:41``)
      * ``DD/MM/YYYY`` (European date only)
      * ``MM/DD/YYYY HH:MM:SS`` (US datetime, fallback)
      * ``MM/DD/YYYY`` (US date only, fallback)

    For ambiguous slash-delimited dates (both day and month <= 12) the
    European (DD/MM/YYYY) interpretation is preferred because 3GPP
    working group data is generated by European organisations. When one
    interpretation produces an invalid calendar date (e.g. month > 12 or
    day > days-in-month), the alternative is tried before giving up.
    Unparseable values return ``None`` rather than raising so a single
    bad cell can't abort an entire sync.
    """
    if value is None:
        return None
    if isinstance(value, datetime):
        return value.date()
    if isinstance(value, date):
        return value
    text = to_text(value)
    if text is None:
        return None

    for fmt in ("%Y-%m-%d", "%Y/%m/%d"):
        try:
            return datetime.strptime(text, fmt).date()
        except ValueError:
            continue

    match = re.fullmatch(
        r"(\d{1,2})/(\d{1,2})/(\d{4})(?:[ T](\d{1,2}):(\d{2}):(\d{2}))?",
        text,
    )
    if match is not None:
        a, b, year_str, hh, mm, ss = match.groups()
        a_i, b_i, year_i = int(a), int(b), int(year_str)
        for day, month in ((a_i, b_i), (b_i, a_i)):
            try:
                if hh is not None:
                    return datetime(
                        year_i, month, day, int(hh), int(mm), int(ss)
                    ).date()
                return date(year_i, month, day)
            except ValueError:
                continue

    return None


def pick_col(header_map: Dict[str, int], candidates: Iterable[str]) -> Optional[int]:
    """Find the first matching column index for a set of header candidates.

    Exact (case-insensitive) matches are preferred; substring matches are used
    as a fallback only when no exact match exists. This avoids ``"Type"``
    matching ``"Type of CR"`` when both columns are present in the sheet.
    """
    candidates_norm = [normalize_header(c) for c in candidates]
    # First pass: prefer exact (case-insensitive) header matches.
    for candidate in candidates_norm:
        if candidate and candidate in header_map:
            return header_map[candidate]
    # Second pass: fall back to substring containment (header contains candidate).
    for candidate in candidates_norm:
        if not candidate:
            continue
        for header, col in header_map.items():
            if candidate in header:
                return col
    return None


_DATE_FIELDS = frozenset({"reservation_date", "uploaded_date"})

# Attribute order varies by emitter (Excel vs openpyxl vs LibreOffice),
# so Id and Target are matched independently rather than in a fixed order.
_REL_TAG_RE = re.compile(
    r'<Relationship\b[^>]*?\bId="(?P<rid>rId\d+)"[^>]*?\bTarget="(?P<target>[^"]+)"',
    re.IGNORECASE,
)
_REL_TAG_RE_REVERSED = re.compile(
    r'<Relationship\b[^>]*?\bTarget="(?P<target>[^"]+)"[^>]*?\bId="(?P<rid>rId\d+)"',
    re.IGNORECASE,
)
_REL_TAG_FALLBACK = re.compile(r"<Relationship\b[^>]*?/>", re.IGNORECASE)
# A workbook-level ``<sheet>`` entry has a ``name`` and an ``r:id`` that
# points at the worksheet's relationships. We only need the first rId
# because TDoc list XLSX always uses the first sheet as the active one.
_SHEET_RID_RE = re.compile(
    r'<sheet\b[^>]*\br:id="(?P<rid>rId\d+)"',
    re.IGNORECASE,
)
# Worksheet ``<hyperlink ref="A12" r:id="rId4"/>`` entries. We capture the
# column letters and the row number so the consumer can pick the right
# column at its own pace.
_HYPERLINK_RE = re.compile(
    r'<hyperlink\b[^>]*\bref="(?P<ref>[A-Z]+\d+)"[^>]*\br:id="(?P<rid>rId\d+)"',
    re.IGNORECASE,
)
_CELL_REF_RE = re.compile(r"^(?P<col>[A-Z]+)(?P<row>\d+)$")


def _extract_tdoc_hyperlinks(xlsx_bytes: bytes) -> Dict[int, Dict[str, str]]:
    """Extract external hyperlinks from a TDoc list XLSX without loading openpyxl.

    Returns a mapping ``{row_number: {column_letter: target_url}}`` for the
    *active* sheet only. The XLSX format stores cell hyperlinks in two places:

    1. ``xl/worksheets/sheetN.xml`` — ``<hyperlink ref="A12" r:id="rId4"/>``
       elements that anchor an external relationship to a cell.
    2. ``xl/worksheets/_rels/sheetN.xml.rels`` — the relationship file that
       maps ``rId4`` to the actual ``Target`` URL.

    We read both files directly from the underlying zip rather than going
    through ``openpyxl.load_workbook(..., read_only=False)`` because
    non-read-only loading is ~30x slower (≈2s vs ≈0.07s for a 425KB fixture
    with 1.6k rows) and we only need a side-channel of URL metadata, not
    the cell-style/formula data openpyxl would otherwise materialise.

    Internal hyperlinks (``location`` attribute, no external ``r:id``) and
    relationship entries that point at comments / drawings are skipped so
    the returned dict only contains real TDoc download URLs.
    """
    result: Dict[int, Dict[str, str]] = {}
    try:
        with zipfile.ZipFile(io.BytesIO(xlsx_bytes)) as zf:
            names = zf.namelist()

            # 1. Find which sheet file corresponds to the active sheet.
            #    Default to the first declared <sheet> when workbook.xml
            #    does not carry an explicit activeTab — openpyxl does the
            #    same and matches what `read_tdoc_sheet` will iterate.
            try:
                wb_xml = zf.read("xl/workbook.xml").decode("utf-8")
                wb_rels = zf.read("xl/_rels/workbook.xml.rels").decode("utf-8")
            except KeyError:
                logger.debug("XLSX missing workbook.xml or its rels; no hyperlinks")
                return result

            rid_to_target: Dict[str, str] = {}
            for m in _REL_TAG_RE.finditer(wb_rels):
                rid_to_target[m.group("rid")] = m.group("target")
            for m in _REL_TAG_RE_REVERSED.finditer(wb_rels):
                rid_to_target.setdefault(m.group("rid"), m.group("target"))
            sheet_rids = [m.group("rid") for m in _SHEET_RID_RE.finditer(wb_xml)]
            sheet_target = next(
                (rid_to_target[rid] for rid in sheet_rids if rid in rid_to_target),
                None,
            )
            if not sheet_target:
                return result

            # Targets may be either relative (``worksheets/sheet1.xml``)
            # or absolute (``/xl/worksheets/sheet1.xml``, as openpyxl
            # writes); normalise to a zip-internal relative path.
            normalised = sheet_target.lstrip("/")
            if normalised.startswith("xl/"):
                sheet_path = normalised
            else:
                sheet_path = f"xl/{normalised}"
            sheet_basename = normalised.rsplit("/", 1)[-1]
            sheet_rels_path = f"xl/worksheets/_rels/{sheet_basename}.rels"

            if sheet_path not in names or sheet_rels_path not in names:
                return result

            # 2. Map rId -> Target URL for this sheet's relationships.
            sheet_rels = zf.read(sheet_rels_path).decode("utf-8")
            rid_to_url: Dict[str, str] = {}
            for m in _REL_TAG_RE.finditer(sheet_rels):
                rid, target = m.group("rid"), m.group("target")
                if target.startswith(("http://", "https://", "ftp://")):
                    rid_to_url[rid] = target
            for m in _REL_TAG_RE_REVERSED.finditer(sheet_rels):
                rid, target = m.group("rid"), m.group("target")
                if target.startswith(("http://", "https://", "ftp://")):
                    rid_to_url.setdefault(rid, target)

            # 3. Walk the sheet XML and pair each <hyperlink> with its URL.
            sheet_xml = zf.read(sheet_path).decode("utf-8")
            for m in _HYPERLINK_RE.finditer(sheet_xml):
                cell_ref = m.group("ref")
                rid = m.group("rid")
                url = rid_to_url.get(rid)
                if not url:
                    continue
                ref_match = _CELL_REF_RE.match(cell_ref)
                if not ref_match:
                    continue
                col_letter = ref_match.group("col")
                row_number = int(ref_match.group("row"))
                result.setdefault(row_number, {})[col_letter] = url
    except (zipfile.BadZipFile, KeyError, ValueError, UnicodeDecodeError) as exc:
        # A bad zip or unexpected layout should not abort the whole sync —
        # the parser can still return rows with ``tdoc_url=None``.
        logger.debug("Hyperlink extraction failed for XLSX: %s", exc)
    return result


def read_tdoc_sheet(xlsx_bytes: bytes) -> List[Dict[str, object]]:
    logger.debug("Reading TDoc XLSX bytes (%s bytes)", len(xlsx_bytes))
    workbook = load_workbook(io.BytesIO(xlsx_bytes), read_only=True, data_only=True)
    if workbook is None or not workbook.sheetnames:
        logger.error("Could not read TDoc list sheet from XLSX file")
        raise RuntimeError("Could not read TDoc list sheet from XLSX file.")

    worksheet = workbook.active

    # Hyperlinks are not exposed in ``read_only`` mode, so pull them from
    # the underlying XLSX zip in a separate, fast side-channel pass.
    # The result is keyed by Excel row number so we can match it against
    # the iteration index below.
    hyperlinks = _extract_tdoc_hyperlinks(xlsx_bytes)

    header_map: Dict[str, int] = {}
    header_row_idx: int | None = None
    for row_idx, row in enumerate(worksheet.iter_rows(values_only=True), start=1):
        potential = {normalize_header(cell): idx for idx, cell in enumerate(row) if normalize_header(cell)}
        if _is_header_row(potential):
            header_map = potential
            header_row_idx = row_idx
            logger.debug("Detected header row at Excel row %s: %s", row_idx, header_map)
            break

    if not header_map:
        logger.error("Could not find header row in TDoc list sheet")
        raise RuntimeError("Could not find header row in TDoc list sheet.")

    col_tdoc = pick_col(header_map, ["Tdoc", "TDoc"])
    if col_tdoc is None:
        logger.error("Could not find TDoc column in TDoc list sheet")
        raise RuntimeError("Could not find TDoc column in TDoc list sheet.")

    # Convert the 0-based TDoc column index to the column letter that the
    # raw-XML hyperlink map is keyed by, so we can pull the per-row URL.
    tdoc_col_letter = _col_index_to_letter(col_tdoc)

    mapping = {
        "title": pick_col(header_map, ["Title"]),
        "source": pick_col(header_map, ["Source"]),
        "type": pick_col(header_map, ["Type"]),
        "status": pick_col(header_map, ["Status", "TDoc Status"]),
        "reservation_date": pick_col(header_map, ["Reservation Date", "Reservation date"]),
        "uploaded_date": pick_col(header_map, ["Uploaded Date", "Uploaded"]),
        "cr_cat": pick_col(header_map, ["CR Cat", "CR category", "Cat"]),
        "is_revision_of": pick_col(header_map, ["Is revision of"]),
        "revised_to": pick_col(header_map, ["Revised to"]),
        "release": pick_col(header_map, ["Release"]),
        "spec": pick_col(header_map, ["Spec"]),
        "version": pick_col(header_map, ["Version"]),
        "related_wis": pick_col(header_map, ["Related WIs", "Work item code"]),
        "cr_num": pick_col(header_map, ["CR"]),
        "cr_pack": pick_col(header_map, ["TSG CR Pack", "TSG CR pack", "CR Pack"]),
    }

    result: List[Dict[str, object]] = []
    skipped_rows = 0
    # Start a fresh iterator at the row *after* the header so the index we
    # pair with the hyperlink map matches the real Excel row number.
    data_rows = worksheet.iter_rows(
        min_row=(header_row_idx or 0) + 1,
        values_only=True,
    )
    for row_index, row in enumerate(data_rows, start=(header_row_idx or 0) + 1):
        raw_tdoc = to_text(row[col_tdoc]) if col_tdoc < len(row) else None
        if not raw_tdoc:
            logger.debug("Skipping empty row %s", row_index)
            continue

        match = CR_ID_RE.search(raw_tdoc)
        if not match:
            logger.debug("Skipping non-TDoc row %s: %s", row_index, raw_tdoc)
            skipped_rows += 1
            continue

        record: Dict[str, object] = {
            "tdoc": match.group(0),
            "tdoc_url": hyperlinks.get(row_index, {}).get(tdoc_col_letter),
        }
        for key, col in mapping.items():
            if col is not None and col < len(row):
                cell_value = row[col]
                if key in _DATE_FIELDS:
                    record[key] = _parse_date_cell(cell_value)
                else:
                    record[key] = to_text(cell_value)
            else:
                record[key] = None
        result.append(record)

    if skipped_rows:
        logger.warning(
            "Skipped %s row(s) with unrecognized TDoc identifier pattern %r; "
            "consider widening CR_ID_RE if upstream conventions have changed.",
            skipped_rows,
            CR_ID_RE.pattern,
        )
    logger.info("Parsed %s TDoc records from XLSX", len(result))
    return result


def _col_index_to_letter(col_idx: int) -> str:
    """Convert a 0-based column index to its Excel column letter.

    Mirrors :func:`openpyxl.utils.get_column_letter` for the 0-based input
    shape used by ``read_tdoc_sheet`` (header cells carry 0-based indices).
    Implemented locally to avoid pulling openpyxl's utils into a hot path
    that only deals with letters.
    """
    if col_idx < 0:
        raise ValueError(f"Column index must be non-negative, got {col_idx}")
    letters: list[str] = []
    n = col_idx + 1
    while n > 0:
        n, rem = divmod(n - 1, 26)
        letters.append(chr(ord("A") + rem))
    return "".join(reversed(letters))
